# Generated by Django 4.2.18 on 2025-01-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('service_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='FieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('label', models.JSONField()),
                ('placeholder', models.JSONField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('option', 'Option (Dropdown)'), ('date', 'Date')], max_length=20)),
                ('validation_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_error_message', models.JSONField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configurations', to='service.service')),
            ],
        ),
    ]
